### ISSUE TITLE
Is it possible to have the 3D model of the enclosure as well?

### ISSUE THREAD

**Issue by rudyferraro** [UltimateHackingKeyboard/trackball-electronics#1]
Hello,

Is it possible to have the 3D model of the enclosure as well? It will help creating custom trackball modules.

Thanks,
Cheers,
Rudy

**Comment by mondalaci** [comment]
Hi Rudy,

We plan to create a module development kit eventually, but in the meantime, [our policy](https://ultimatehackingkeyboard.com/knowledgebase?q=cad) is to not share the 3D CAD files of parts that are in production.

However, we want to make improvements to the trackball module. Please shoot an email to support@ultimatehackingkeyboard.com and let us know what you're up to.
